"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import AddressAutocomplete from "@/components/booking/AddressAutocomplete";
import PassengerCounter from "@/components/booking/PassengerCounter";
import LuggageWarning from "@/components/booking/LuggageWarning";
import { csrfFetch } from "@/lib/client/csrf-fetch";
import { useLanguage } from "@/lib/i18n/LanguageContext";
import { isCustomerServiceEnabled } from "@/lib/feature-flags";

type Child = { fullName: string; age: number; specialRequirements: string };
type FormState = {
  customerName: string; customerPhone: string; customerEmail: string; customerPhoneCode: string; languagePref: string;
  serviceType: string; pickupAddress: string; dropoffAddress: string; pickupLat: number | null; pickupLng: number | null; dropoffLat: number | null; dropoffLng: number | null;
  scheduledRide: boolean; scheduledDate: string; scheduledTime: string; passengerCount: number; smallBags: number; largeBags: number;
  seniorPassenger: boolean; ztpCardHolder: boolean; wheelchairUser: boolean; companionRequired: boolean; companionCount: number; medicalAppointment: boolean;
  assistanceLevel: string | null; wheelchairType: string | null; canTransferToSeat: boolean | null; wavRequired: boolean; passengerRemainsInWheelchair: boolean;
  hospitalName: string; department: string; appointmentDate: string; appointmentTime: string; tripType: string | null; returnDate: string; returnTime: string;
  waitingTimeRequired: boolean; waitingDuration: string | null; customWaitingDuration: string; recurrence: string | null; recurrenceType: string | null; recurrenceCustom: string;
  flightNumber: string; airline: string; waitAndGreet: boolean; educationalDestinationValidated: boolean; educationalInstitutionName: string; institutionAddress: string;
  parentFullName: string; parentPrimaryPhone: string; parentEmergencyPhone: string; parentEmail: string; specialNotes: string; paymentMethod: string; cashAgreed: boolean;
};

function marketNow() {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Bratislava", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date());
  const value = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${value.year}-${value.month}-${value.day}T${value.hour}:${value.minute}`;
}

const initial = (): FormState => ({ customerName: "", customerPhone: "", customerEmail: "", customerPhoneCode: "+421", languagePref: "sk", serviceType: "STANDARD", pickupAddress: "", dropoffAddress: "", pickupLat: null, pickupLng: null, dropoffLat: null, dropoffLng: null, scheduledRide: false, scheduledDate: marketNow().slice(0, 10), scheduledTime: marketNow().slice(11, 16), passengerCount: 1, smallBags: 0, largeBags: 0, seniorPassenger: false, ztpCardHolder: false, wheelchairUser: false, companionRequired: false, companionCount: 0, medicalAppointment: false, assistanceLevel: null, wheelchairType: null, canTransferToSeat: null, wavRequired: false, passengerRemainsInWheelchair: false, hospitalName: "", department: "", appointmentDate: "", appointmentTime: "", tripType: null, returnDate: "", returnTime: "", waitingTimeRequired: false, waitingDuration: null, customWaitingDuration: "", recurrence: null, recurrenceType: null, recurrenceCustom: "", flightNumber: "", airline: "", waitAndGreet: false, educationalDestinationValidated: false, educationalInstitutionName: "", institutionAddress: "", parentFullName: "", parentPrimaryPhone: "", parentEmergencyPhone: "", parentEmail: "", specialNotes: "", paymentMethod: "CASH", cashAgreed: false });

export default function NewPhoneBookingPage() {
  const router = useRouter(); const { t, locale } = useLanguage(); const [form, setForm] = useState<FormState>(initial); const keyRef = useRef("");
  const [children, setChildren] = useState<Child[]>([{ fullName: "", age: 0, specialRequirements: "" }]);
  const [quote, setQuote] = useState<any>(null); const [quoteError, setQuoteError] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const translate = (key: string, fallback: string) => t(`dispatch.form.${key}`, fallback);
  function change<K extends keyof FormState>(key: K, value: FormState[K]) { keyRef.current = ""; setForm((prior) => ({ ...prior, [key]: value })); }

  useEffect(() => {
    if (form.pickupAddress.trim().length < 3 || form.dropoffAddress.trim().length < 3) { setQuote(null); setQuoteError(""); return; }
    let cancelled = false; const timer = setTimeout(async () => {
      try {
        const response = await csrfFetch("dispatch_operator", "/api/dispatch/bookings/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pickupAddress: form.pickupAddress, dropoffAddress: form.dropoffAddress, serviceType: form.serviceType, scheduledDate: form.scheduledDate, scheduledTime: form.scheduledTime, waitingDuration: form.waitingTimeRequired ? form.waitingDuration : null, customWaitingDuration: form.customWaitingDuration || null, assistanceLevel: form.assistanceLevel, waitAndGreet: form.waitAndGreet, recurrenceType: form.recurrenceType || form.recurrence, recurrenceCustom: form.recurrenceCustom || null, returnDate: form.returnDate || null, returnTime: form.returnTime || null }) });
        const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || translate("quoteError", "Quote unavailable")); if (!cancelled) { setQuote(data.quote); setQuoteError(""); }
      } catch (reason) { if (!cancelled) { setQuote(null); setQuoteError(reason instanceof Error ? reason.message : translate("quoteError", "Quote unavailable")); } }
    }, 400);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [form.pickupAddress, form.dropoffAddress, form.serviceType, form.scheduledDate, form.scheduledTime, form.waitingTimeRequired, form.waitingDuration, form.customWaitingDuration, form.assistanceLevel, form.waitAndGreet, form.recurrenceType, form.recurrence, form.recurrenceCustom, form.returnDate, form.returnTime]);

  function setChild(index: number, key: keyof Child, value: string | number) { keyRef.current = ""; setChildren((prior) => prior.map((item, i) => i === index ? { ...item, [key]: value } : item)); }
  function childCount(count: number) { change("passengerCount", count); if (form.serviceType === "CHILDREN") setChildren((prior) => Array.from({ length: count }, (_, index) => prior[index] || { fullName: "", age: 0, specialRequirements: "" })); }
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    if (form.serviceType === "CHILDREN" && (!form.educationalDestinationValidated || children.length !== form.passengerCount || children.some((child) => !child.fullName.trim()))) { setBusy(false); setError(translate("childrenRequired", "Add a verified educational destination and each child's name and age.")); return; }
    if (form.paymentMethod === "CASH" && !form.cashAgreed) { setBusy(false); setError(translate("cashRequired", "Cash payment requires customer agreement.")); return; }
    if (!keyRef.current) keyRef.current = crypto.randomUUID();
    const [date, time] = [form.scheduledDate, form.scheduledTime];
    const payload = { ...form, customerEmail: form.customerEmail || null, scheduledDate: date, scheduledTime: time, pickupDate: date, pickupTime: time, scheduledRide: form.scheduledRide || form.serviceType === "CHILDREN", luggageType: form.largeBags > 0 ? "LARGE" : form.smallBags > 0 ? "SMALL" : "NONE", waitingTimeRequired: Boolean(form.waitingTimeRequired), childrenDetails: form.serviceType === "CHILDREN" ? children.map((child) => ({ ...child, specialRequirements: child.specialRequirements || null })) : undefined, childFullName: children[0]?.fullName || null, childAge: children[0]?.age ?? null, parentFullName: form.parentFullName || null, guardianName: form.parentFullName || null, parentPrimaryPhone: form.parentPrimaryPhone || null, guardianPhone: form.parentPrimaryPhone || null, parentEmergencyPhone: form.parentEmergencyPhone || null, guardianEmergencyPhone: form.parentEmergencyPhone || null, parentEmail: form.parentEmail || null, guardianEmail: form.parentEmail || null, educationalDestinationValidated: form.serviceType === "CHILDREN" && form.educationalDestinationValidated, institutionName: form.educationalInstitutionName || null, institutionAddress: form.institutionAddress || null, estimatedPrice: quote?.totalFare };
    const response = await csrfFetch("dispatch_operator", "/api/dispatch/bookings", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": keyRef.current }, body: JSON.stringify(payload) });
    const data = await response.json().catch(() => ({})); setBusy(false);
    if (!response.ok) { const code = data.code || "unknown"; setError(t(`dispatch.errors.${code}`, data.error || translate("createError", "Could not create booking."))); return; }
    if (data.processing || !data.booking?.id) { setBusy(false); setError(translate("processing", "This booking request is still processing. Retry shortly; the same request key prevents a duplicate.")); return; }
    keyRef.current = ""; router.push(`/dispatch/bookings/${data.booking.id}`);
  }

  const serviceOptions = [["STANDARD", t("services.taxi.title", "Standard Taxi")], ["ACCESSIBLE", t("services.accessible.title", "Accessible transport")], ["SENIOR", t("services.accessible.title", "Senior assisted transport")], ["AIRPORT", t("services.airport.title", "Airport transfer")], ...(isCustomerServiceEnabled("CHILDREN") ? [["CHILDREN", t("services.children.title", "Children Transport")]] : [])];
  const field = (key: keyof FormState, label: string, props: React.InputHTMLAttributes<HTMLInputElement> = {}) => <label className="block text-sm font-semibold">{label}<input {...props} value={String(form[key] ?? "")} onChange={(event) => change(key, (props.type === "number" ? Number(event.target.value) : event.target.value) as any)} className="mt-1 min-h-11 w-full rounded-lg border px-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-700" /></label>;
  const check = (key: keyof FormState, label: string) => <label className="flex min-h-11 items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={Boolean(form[key])} onChange={(event) => change(key, event.target.checked as any)} className="h-5 w-5"/>{label}</label>;
  const money = (amount: number) => new Intl.NumberFormat(locale, { style: "currency", currency: "EUR" }).format(amount);

  return <form onSubmit={submit} className="space-y-5" aria-labelledby="new-phone-booking-heading"><header><h1 id="new-phone-booking-heading" className="text-3xl font-black text-drivo-navy">{t("dispatch.newBooking", "New Phone Booking")}</h1><p className="mt-1 text-sm text-slate-600">{translate("secureQuote", "Fare is calculated by Drivo's server-side pricing engine.")}</p></header>
    {error && <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-900">{error}</p>}
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("customer", "Customer")}</legend><div className="grid gap-4 md:grid-cols-2">{field("customerName", translate("name", "Full name"), { required: true, minLength: 2, maxLength: 120, autoComplete: "name" })}{field("customerPhone", translate("phone", "Phone"), { required: true, minLength: 6, maxLength: 40, type: "tel", autoComplete: "tel-national", placeholder: "9xx xxx xxx" })}<label className="text-sm font-semibold">{translate("countryCode", "Country code")}<select value={form.customerPhoneCode} onChange={(event) => change("customerPhoneCode", event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option>+421</option><option>+420</option><option>+49</option><option>+44</option><option>+380</option></select></label>{field("customerEmail", translate("emailOptional", "Email (optional)"), { type: "email", maxLength: 254, autoComplete: "email" })}<label className="text-sm font-semibold">{translate("language", "Preferred language")}<select value={form.languagePref} onChange={(event) => change("languagePref", event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3">{["sk", "de", "uk", "en"].map((value) => <option key={value} value={value}>{value.toUpperCase()}</option>)}</select></label></div></fieldset>
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("trip", "Trip")}</legend><div className="grid gap-4 md:grid-cols-2"><AddressAutocomplete id="dispatch-pickup" label={translate("pickup", "Pickup address")} value={form.pickupAddress} onChange={(value) => change("pickupAddress", value)} placeholder={translate("addressPlaceholder", "Start typing an address")} onSelect={(_value, suggestion) => { if (suggestion?.lat != null && suggestion.lng != null) { change("pickupLat", suggestion.lat); change("pickupLng", suggestion.lng); } }}/><AddressAutocomplete id="dispatch-dropoff" label={translate("dropoff", "Destination")} value={form.dropoffAddress} onChange={(value) => change("dropoffAddress", value)} placeholder={translate("addressPlaceholder", "Start typing an address")} onSelect={(_value, suggestion) => { if (suggestion?.lat != null && suggestion.lng != null) { change("dropoffLat", suggestion.lat); change("dropoffLng", suggestion.lng); } }}/><label className="flex min-h-11 items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={form.scheduledRide} onChange={(event) => change("scheduledRide", event.target.checked)} className="h-5 w-5"/>{translate("scheduled", "Scheduled ride")}</label>{field("scheduledDate", translate("date", "Pickup date"), { required: true, type: "date" })}{field("scheduledTime", translate("time", "Pickup time"), { required: true, type: "time" })}<label className="text-sm font-semibold">{translate("service", "Service")}<select required value={form.serviceType} onChange={(event) => { change("serviceType", event.target.value); if (event.target.value !== "CHILDREN") { change("educationalDestinationValidated", false); } }} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3">{serviceOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></fieldset>
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("passengers", "Passengers and luggage")}</legend><PassengerCounter value={form.passengerCount} onChange={childCount} max={6} label={translate("passengers", "Passengers")}/><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("smallBags", translate("smallBags", "Small bags"), { type: "number", min: 0, max: 12 })}{field("largeBags", translate("largeBags", "Large bags"), { type: "number", min: 0, max: 12 })}</div><LuggageWarning passengers={form.passengerCount + form.companionCount} luggage={form.smallBags + form.largeBags > 0 ? "large" : "none"} onSwitchService={() => change("serviceType", "AIRPORT")}/></fieldset>
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("accessibility", "Accessibility and assistance")}</legend><div className="grid gap-3 sm:grid-cols-2">{check("seniorPassenger", translate("senior", "Senior passenger"))}{check("ztpCardHolder", translate("ztp", "ZTP card holder"))}{check("wheelchairUser", translate("wheelchair", "Wheelchair user"))}{check("companionRequired", translate("companion", "Companion required"))}{check("medicalAppointment", translate("medical", "Medical appointment"))}{check("wavRequired", translate("wavRequired", "Wheelchair-accessible vehicle required"))}{check("passengerRemainsInWheelchair", translate("remainsWheelchair", "Passenger remains in wheelchair"))}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">{translate("companionCount", "Companion count")}<input type="number" min={0} max={3} value={form.companionCount} onChange={(event) => change("companionCount", Number(event.target.value))} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">{translate("assistanceLevel", "Assistance level")}<select value={form.assistanceLevel || ""} onChange={(event) => change("assistanceLevel", event.target.value || null)} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="">{translate("none", "None")}</option><option value="LIGHT">{translate("light", "Light")}</option><option value="DOOR_TO_DOOR">{translate("doorToDoor", "Door to door")}</option><option value="BOARDING_HELP">{translate("boardingHelp", "Boarding help")}</option></select></label><label className="text-sm font-semibold">{translate("wheelchairType", "Wheelchair type")}<select value={form.wheelchairType || ""} onChange={(event) => change("wheelchairType", event.target.value || null)} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="">{translate("none", "None")}</option>{["MANUAL", "ELECTRIC", "FOLDABLE"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold">{translate("transfer", "Can transfer to a vehicle seat?")}<select value={form.canTransferToSeat === null ? "" : String(form.canTransferToSeat)} onChange={(event) => change("canTransferToSeat", event.target.value === "" ? null : event.target.value === "true")} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="">{translate("unknown", "Not specified")}</option><option value="true">{translate("yes", "Yes")}</option><option value="false">{translate("no", "No")}</option></select></label></div></fieldset>
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("medicalReturn", "Medical trip and return")}</legend>{check("medicalAppointment", translate("medical", "Medical appointment"))}<div className="mt-3 grid gap-4 sm:grid-cols-2">{field("hospitalName", translate("hospital", "Hospital / clinic"), { maxLength: 120 })}{field("department", translate("department", "Department"), { maxLength: 120 })}{field("appointmentDate", translate("appointmentDate", "Appointment date"), { type: "date" })}{field("appointmentTime", translate("appointmentTime", "Appointment time"), { type: "time" })}<label className="text-sm font-semibold">{translate("tripType", "Trip type")}<select value={form.tripType || ""} onChange={(event) => change("tripType", event.target.value || null)} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="">{translate("oneWay", "One way")}</option><option value="GO_ONLY">{translate("goOnly", "Go only")}</option><option value="GO_RETURN">{translate("goReturn", "Return trip")}</option><option value="WAIT_RETURN">{translate("waitReturn", "Wait and return")}</option></select></label>{field("returnDate", translate("returnDate", "Return date"), { type: "date" })}{field("returnTime", translate("returnTime", "Return time"), { type: "time" })}<label className="text-sm font-semibold">{translate("waiting", "Reserved waiting time")}<select value={form.waitingDuration || ""} onChange={(event) => { change("waitingDuration", event.target.value || null); change("waitingTimeRequired", Boolean(event.target.value)); }} className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3"><option value="">{translate("none", "None")}</option>{["30_MINUTES", "1_HOUR", "2_HOURS", "3_HOURS", "4_HOURS", "CUSTOM"].map((value) => <option key={value} value={value}>{translate(`waiting.${value}`, value.replaceAll("_", " "))}</option>)}</select></label>{form.waitingDuration === "CUSTOM" && field("customWaitingDuration", translate("customWaiting", "Custom waiting (minutes)"), { inputMode: "numeric", maxLength: 80 })}</div></fieldset>
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("airport", "Airport service")}</legend><div className="grid gap-4 sm:grid-cols-2">{field("flightNumber", translate("flight", "Flight number"))}{field("airline", translate("airline", "Airline"))}{check("waitAndGreet", translate("meetGreet", "Meet & Greet"))}</div></fieldset>
    {form.serviceType === "CHILDREN" && <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("children", "Children Transport")}</legend>{check("educationalDestinationValidated", translate("verifiedSchool", "Educational destination verified"))}{field("educationalInstitutionName", translate("institution", "Educational institution"), { required: true, maxLength: 160 })}{field("institutionAddress", translate("institutionAddress", "Institution address"), { required: true, maxLength: 240 })}<div className="mt-3 space-y-3">{children.map((child, index) => <fieldset key={index} className="grid gap-3 rounded-xl border p-3 sm:grid-cols-3"><legend className="px-1 text-sm font-bold">{translate("child", "Child")} {index + 1}</legend><label className="text-sm font-semibold">{translate("childName", "Full name")}<input required value={child.fullName} onChange={(event) => setChild(index, "fullName", event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">{translate("childAge", "Age")}<input required type="number" min={0} max={18} value={child.age} onChange={(event) => setChild(index, "age", Number(event.target.value))} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><label className="text-sm font-semibold">{translate("childRequirements", "Special requirements")}<input value={child.specialRequirements} onChange={(event) => setChild(index, "specialRequirements", event.target.value)} maxLength={500} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label></fieldset>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2">{field("parentFullName", translate("parentName", "Parent / guardian"))}{field("parentPrimaryPhone", translate("parentPhone", "Parent phone"), { type: "tel" })}{field("parentEmergencyPhone", translate("emergencyPhone", "Emergency phone"), { type: "tel" })}{field("parentEmail", translate("parentEmail", "Parent email"), { type: "email" })}</div></fieldset>}
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("payment", "Payment")}</legend><div className="grid gap-3 sm:grid-cols-3">{[["CASH", t("dispatch.payOnRide", "Pay on Ride")], ["INVOICE", t("dispatch.invoice", "Invoice")], ["CARD", t("dispatch.secureCard", "Card · Secure Payment Link")]].map(([value, label]) => <label key={value} className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border p-3 ${form.paymentMethod === value ? "border-teal-700 bg-teal-50" : ""}`}><input type="radio" name="payment" value={value} checked={form.paymentMethod === value} onChange={() => change("paymentMethod", value)} className="h-5 w-5"/>{label}</label>)}</div>{form.paymentMethod === "CASH" && check("cashAgreed", translate("cashAgreement", "Customer agrees to pay before the journey starts"))}</fieldset>
    <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-2 text-lg font-black">{translate("notes", "Notes")}</legend><label className="block text-sm font-semibold">{translate("specialNotes", "Special notes (do not enter card details)")}<textarea value={form.specialNotes} onChange={(event) => change("specialNotes", event.target.value)} maxLength={500} rows={3} className="mt-1 w-full rounded-lg border p-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-700"/></label></fieldset>
    <section className="rounded-2xl border bg-white p-4" aria-labelledby="quote-heading"><h2 id="quote-heading" className="text-lg font-black">{translate("fareBreakdown", "Authoritative fare estimate")}</h2>{quoteError && <p role="status" className="mt-2 text-sm text-amber-900">{quoteError}</p>}{quote && <div className="mt-3 grid gap-2 sm:grid-cols-2"><p>{translate("distance", "Distance")}: {quote.distanceKm} km</p><p>{translate("duration", "Route duration")}: {quote.durationMinutes} min</p><p className="font-black">{translate("total", "Total")}: {money(quote.totalFare)}</p><p>{translate("assistanceFee", "Driver Assistance")}: {money(quote.breakdown.optionalServiceCharges.assistedTransport || 0)}</p><p>{translate("waitingCharge", "Waiting Charge")}: {money(quote.breakdown.waitingCharge)}</p></div>}</section>
    <div className="flex flex-wrap gap-3"><button disabled={busy} className="min-h-12 rounded-xl bg-drivo-navy px-6 font-bold text-white disabled:opacity-50">{busy ? t("common.loading", "Loading") : t("dispatch.createBooking", "Create Phone Booking")}</button><p className="self-center text-xs text-slate-600">{translate("fareNotice", "The server recalculates and stores the final fare when you create the booking.")}</p></div>
  </form>;
}
