"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { GoogleMap, Marker, Polyline, useJsApiLoader } from "@react-google-maps/api";
import { NAVIGATION_CONFIG, navigationQuality, type NavigationQuality } from "@/lib/navigation/config";
import type { NavigationRoute } from "@/lib/navigation/routes";

type BookingLike = { id: string; status: string; paymentMethod: string; bookingRef: string; pickupAddress?: string; dropoffAddress?: string; };
const mapStyle = { width: "100%", height: "min(52vh, 460px)", borderRadius: "20px" };
function decodePolyline(encoded: string) { let index = 0, lat = 0, lng = 0; const path: google.maps.LatLngLiteral[] = []; while (index < encoded.length) { let shift = 0, result = 0, byte = 0; do { byte = encoded.charCodeAt(index++) - 63; result |= (byte & 31) << shift; shift += 5; } while (byte >= 32); lat += (result & 1) ? ~(result >> 1) : result >> 1; shift = 0; result = 0; do { byte = encoded.charCodeAt(index++) - 63; result |= (byte & 31) << shift; shift += 5; } while (byte >= 32); lng += (result & 1) ? ~(result >> 1) : result >> 1; path.push({ lat: lat / 1e5, lng: lng / 1e5 }); } return path; }
function formatDistance(meters: number) { return meters >= 1000 ? `${(meters / 1000).toFixed(1)} km` : `${Math.round(meters)} m`; }
function formatEta(seconds: number) { const minutes = Math.max(1, Math.round(seconds / 60)); return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)} h ${minutes % 60} min`; }

export function DriverNavigationMap({ route }: { route: NavigationRoute | null }) {
  const { isLoaded, loadError } = useJsApiLoader({ id: "google-map-script", googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || "", libraries: [], region: "SK" });
  const mapRef = useRef<google.maps.Map | null>(null);
  const path = useMemo(() => route?.polyline ? decodePolyline(route.polyline) : [], [route]);
  useEffect(() => { if (!mapRef.current || path.length < 2) return; const bounds = new google.maps.LatLngBounds(); path.forEach((point) => bounds.extend(point)); mapRef.current.fitBounds(bounds, 56); }, [path]);
  if (loadError || !process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY) return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" role="status">Map unavailable. Use the external navigation link below.</div>;
  if (!isLoaded) return <div className="flex min-h-52 items-center justify-center rounded-2xl bg-gray-100 text-sm text-gray-600" role="status">Loading Drivo mapâ€¦</div>;
  const center = route?.origin || route?.destination || { lat: 48.1486, lng: 17.1077 };
  return <div className="overflow-hidden rounded-2xl border border-gray-200 shadow-sm"><GoogleMap mapContainerStyle={mapStyle} center={center} zoom={14} options={{ mapTypeControl: false, streetViewControl: false, fullscreenControl: true, zoomControl: true }} onLoad={(map) => { mapRef.current = map; }} onUnmount={() => { mapRef.current = null; }}>
    {route?.origin && <Marker position={route.origin} title="Driver position" label={{ text: "D", color: "#fff", fontWeight: "700" }} />}
    {route?.destination && <Marker position={route.destination} title={route.leg === "TO_PICKUP" ? "Pickup" : "Destination"} label={{ text: route.leg === "TO_PICKUP" ? "P" : "D", color: "#fff", fontWeight: "700" }} />}
    {path.length > 1 && <Polyline path={path} options={{ strokeColor: "#087f5b", strokeOpacity: 0.9, strokeWeight: 6 }} />}
  </GoogleMap></div>;
}

export function DriverNavigationPanel({ booking, updating, realtimeStatus, locationStatus, onStatusUpdate, onCashConfirm }: { booking: BookingLike; updating: boolean; realtimeStatus: "connecting" | "connected" | "offline"; locationStatus?: "idle" | "tracking" | "blocked" | "unsupported" | "error"; onStatusUpdate: (id: string, status: string) => void; onCashConfirm: () => void; }) {
  const [route, setRoute] = useState<NavigationRoute | null>(null); const [waitingSince, setWaitingSince] = useState<string | null>(null); const [waitingNow, setWaitingNow] = useState(() => Date.now()); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [quality, setQuality] = useState<NavigationQuality>("UNAVAILABLE"); const requestSeq = useRef(0); const abortRef = useRef<AbortController | null>(null);
  const fetchRoute = useCallback(async () => { const seq = ++requestSeq.current; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const permissionDenied = locationStatus === "blocked"; setLoading(true); setError(""); try { const response = await fetch(`/api/driver/navigation/route?bookingId=${encodeURIComponent(booking.id)}`, { cache: "no-store", credentials: "include", signal: controller.signal }); const data = await response.json().catch(() => ({})); if (seq !== requestSeq.current) return; if (!response.ok) { setRoute(null); setWaitingSince(null); setQuality(permissionDenied ? "PERMISSION_DENIED" : data.code === "DRIVER_LOCATION_STALE" ? "STALE" : "UNAVAILABLE"); setError(data.error || "Navigation is temporarily unavailable"); return; } setRoute(data.route || null); setWaitingSince(data.waitingSince || null); setQuality(navigationQuality({ accuracy: data.gps?.accuracy, receivedAt: data.gps?.receivedAt, permissionDenied })); } catch (caught) { if ((caught as Error).name !== "AbortError" && seq === requestSeq.current) { setQuality(permissionDenied ? "PERMISSION_DENIED" : "UNAVAILABLE"); setError("Connection interrupted. Reconnecting..."); } } finally { if (seq === requestSeq.current) setLoading(false); } }, [booking.id, locationStatus]);
  useEffect(() => { setRoute(null); setWaitingSince(null); void fetchRoute(); const timer = setInterval(() => void fetchRoute(), NAVIGATION_CONFIG.routeMaxAgeSeconds * 500); return () => { clearInterval(timer); abortRef.current?.abort(); }; }, [booking.id, booking.status, fetchRoute]);
  useEffect(() => { if (!waitingSince) return; const timer = setInterval(() => setWaitingNow(Date.now()), 1000); return () => clearInterval(timer); }, [waitingSince]);
  const action = booking.status === "ASSIGNED" || booking.status === "CONFIRMED" ? { label: "Start route to pickup", status: "DRIVER_ENROUTE" } : booking.status === "DRIVER_ENROUTE" ? { label: "Arrived at pickup", status: "ARRIVED" } : booking.status === "ARRIVED" ? (booking.paymentMethod === "CASH" ? { label: "Confirm cash and start trip", status: "CASH_CONFIRM" } : { label: "Start trip", status: "IN_PROGRESS" }) : booking.status === "IN_PROGRESS" ? { label: "Complete trip", status: "COMPLETED" } : null;
  const external = route?.destination ? `https://www.google.com/maps/dir/?api=1&destination=${route.destination.lat},${route.destination.lng}&travelmode=driving` : null;
  return <section className="mb-4 rounded-[2rem] bg-white p-3 shadow-lg ring-1 ring-gray-200" aria-labelledby="driver-navigation-title">
    <div className="flex items-center justify-between gap-3 px-2 py-2"><div><p className="text-[11px] font-black uppercase tracking-wide text-gray-500">Drivo navigation</p><h3 id="driver-navigation-title" className="text-lg font-black text-gray-900">{route?.leg === "TO_DROPOFF" ? "To destination" : route?.leg === "AT_PICKUP" ? "At pickup Â· waiting" : "To pickup"}</h3></div><span aria-live="polite" className="rounded-full bg-gray-100 px-3 py-2 text-xs font-bold text-gray-700">{realtimeStatus === "connected" ? "Connected" : realtimeStatus === "connecting" ? "Reconnecting" : "Realtime unavailable"}</span></div>
    <DriverNavigationMap route={route} />
    <div className="grid grid-cols-2 gap-2 px-2 py-3 text-sm"><div><span className="block text-[11px] font-bold uppercase text-gray-500">Distance</span><strong>{route ? formatDistance(route.distanceMeters) : "â€”"}</strong></div><div><span className="block text-[11px] font-bold uppercase text-gray-500">ETA</span><strong>{route ? formatEta(route.durationSeconds) : "â€”"}</strong></div></div>
    <div className="px-2 text-xs" aria-live="polite"><span className="font-bold">GPS: </span>{quality === "GOOD" ? "Good" : quality === "LOW_ACCURACY" ? "Low accuracy" : quality === "STALE" ? "Location stale" : quality === "PERMISSION_DENIED" ? "Permission denied" : "Unavailable"}{loading ? " Â· Refreshing route" : ""}{error ? ` Â· ${error}` : ""}</div>
    {route?.leg === "AT_PICKUP" && <div className="mt-3 rounded-2xl bg-amber-50 p-3 text-sm font-bold text-amber-900" role="status">Waiting state is controlled by the server-arrived trip status. {waitingSince ? <>Waiting since {new Date(waitingSince).toLocaleTimeString()} ({Math.max(0, Math.floor((waitingNow - new Date(waitingSince).getTime()) / 60000))} min elapsed).</> : "Waiting start time unavailable."} Keep the passenger information panel visible.</div>}
    <div className="mt-3 grid gap-2 px-2 sm:grid-cols-2">{action && <button type="button" onClick={() => action.status === "CASH_CONFIRM" ? onCashConfirm() : onStatusUpdate(booking.id, action.status)} disabled={updating} className="min-h-12 rounded-2xl bg-green-700 px-4 py-3 text-sm font-black text-white hover:bg-green-800 disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-700">{updating ? "Updatingâ€¦" : action.label}</button>}{external && <a href={external} target="_blank" rel="noopener noreferrer" className="flex min-h-12 items-center justify-center rounded-2xl border border-gray-300 px-4 py-3 text-sm font-black text-gray-900 hover:bg-gray-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-700">Open in Google Maps</a>}</div>
  </section>;
}
