import { z } from "zod";

export const BookingSchema = z.object({
  serviceType: z.enum([
    "STANDARD",
    "ACCESSIBLE",
    "SENIOR",
    "CHILDREN",
    "AIRPORT",
    "RENTAL",
  ]),

  pickupAddress: z.string().min(3, "Pickup address required"),
  dropoffAddress: z.string().min(3, "Drop-off address required"),

  pickupLat: z.number().optional().nullable(),
  pickupLng: z.number().optional().nullable(),
  dropoffLat: z.number().optional().nullable(),
  dropoffLng: z.number().optional().nullable(),

  scheduledDate: z.string().min(1, "Date required"),
  scheduledTime: z.string().min(1, "Time required"),
  passengerCount: z.number().min(1).max(6),
  luggageType: z.enum(["NONE", "SMALL", "LARGE"]).default("NONE"),
  smallBags: z.number().min(0).max(12).default(0),
  largeBags: z.number().min(0).max(12).default(0),
  wheelchairNeeded: z.boolean().default(false),
  seniorPassenger: z.boolean().default(false),
  ztpCardHolder: z.boolean().default(false),
  wheelchairUser: z.boolean().default(false),
  companionRequired: z.boolean().default(false),
  medicalAppointment: z.boolean().default(false),
  waitingTimeRequired: z.boolean().default(false),
  assistanceLevel: z.enum(["LIGHT", "DOOR_TO_DOOR", "BOARDING_HELP"]).optional().nullable(),
  wheelchairType: z.enum(["MANUAL", "ELECTRIC", "FOLDABLE"]).optional().nullable(),
  canTransferToSeat: z.boolean().optional().nullable(),
  wavRequired: z.boolean().default(false),
  passengerRemainsInWheelchair: z.boolean().default(false),
  companionCount: z.number().min(0).max(3).default(0),
  hospitalName: z.string().max(120).optional().nullable(),
  department: z.string().max(120).optional().nullable(),
  appointmentDate: z.string().optional().nullable(),
  appointmentTime: z.string().optional().nullable(),
  tripType: z.enum(["GO_ONLY", "GO_RETURN", "WAIT_RETURN"]).optional().nullable(),
  returnDate: z.string().optional().nullable(),
  returnTime: z.string().optional().nullable(),
  waitingDuration: z.enum(["30_MINUTES", "1_HOUR", "2_HOURS", "3_HOURS", "4_HOURS", "CUSTOM"]).optional().nullable(),
  customWaitingDuration: z.string().max(80).optional().nullable(),
  scheduledRide: z.boolean().default(false),
  recurrence: z.enum(["ONE_TIME", "DAILY", "WEEKLY", "MONTHLY", "CUSTOM"]).optional().nullable(),
  recurrenceCustom: z.string().max(120).optional().nullable(),
  childrenDetails: z.array(
    z.object({
      fullName: z.string().min(1).max(120),
      age: z.coerce.number().min(0).max(18),
      specialRequirements: z.string().max(500).nullable().optional(),
    })
  ).max(6).optional().nullable(),
  childFullName: z.string().max(120).optional().nullable(),
  childName: z.string().max(120).optional().nullable(),
  childAge: z.number().min(0).max(18).optional().nullable(),
  childSpecialRequirements: z.string().max(500).optional().nullable(),
  parentFullName: z.string().max(120).optional().nullable(),
  guardianName: z.string().max(120).optional().nullable(),
  parentPrimaryPhone: z.string().max(40).optional().nullable(),
  guardianPhone: z.string().max(40).optional().nullable(),
  parentEmergencyPhone: z.string().max(40).optional().nullable(),
  guardianEmergencyPhone: z.string().max(40).optional().nullable(),
  parentEmail: z.string().email().optional().nullable(),
  guardianEmail: z.string().email().optional().nullable(),
  educationalInstitutionName: z.string().max(160).optional().nullable(),
  institutionName: z.string().max(160).optional().nullable(),
  institutionAddress: z.string().max(240).optional().nullable(),
  educationalDestinationValidated: z.boolean().default(false),
  pickupDate: z.string().optional().nullable(),
  pickupTime: z.string().optional().nullable(),
  recurrenceType: z.enum(["ONE_TIME", "DAILY", "WEEKLY", "MONTHLY", "CUSTOM"]).optional().nullable(),

  flightNumber: z.string().optional().nullable(),
  airline: z.string().optional().nullable(),
  waitAndGreet: z.boolean().default(false),

  customerName: z.string().min(2, "Name required"),
  customerEmail: z.string().trim().email("Valid customer email required"),
  customerPhone: z.string().min(6, "Phone required"),
  customerPhoneCode: z.string().default("+421"),
  languagePref: z.string().default("sk"),
  specialNotes: z.string().max(500).optional().nullable(),

  paymentMethod: z.enum(["CARD", "CASH", "INVOICE"]),
  cashAgreed: z.boolean().default(false),
  estimatedPrice: z.number().optional().nullable(),
  fareBreakdown: z.unknown().optional().nullable(),
});

export type BookingInput = z.infer<typeof BookingSchema>;
