const fs = require("fs"); const path = require("path"); const root = process.cwd();
const read = (p) => fs.readFileSync(path.join(root, p), "utf8"); const exists = (p) => fs.existsSync(path.join(root, p)); let checks = 0;
function ok(label, condition) { if (!condition) throw new Error(`FAIL: ${label}`); checks++; }
const pkg = JSON.parse(read("package.json")); const schema = read("prisma/schema.prisma"); const server = read("realtime/server.ts"); const worker = read("workers/realtime-worker.ts"); const relay = read("lib/outbox-relay.ts"); const auth = read("lib/realtime/auth.ts"); const contracts = read("lib/realtime/contracts.ts"); const dashboard = read("app/driver/dashboard/page.tsx");
ok("realtime branch files", exists("realtime/server.ts") && exists("workers/realtime-worker.ts"));
ok("socket server dependency", Boolean(pkg.dependencies["socket.io"])); ok("redis dependencies", Boolean(pkg.dependencies.ioredis && pkg.dependencies["@socket.io/redis-adapter"])); ok("bullmq dependency", Boolean(pkg.dependencies.bullmq)); ok("tsx dependency", Boolean(pkg.dependencies.tsx));
ok("scripts", ["realtime:start","worker:start","worker:outbox","test:phase3d"].every((k) => pkg.scripts[k]));
ok("websocket only", server.includes("transports: [\"websocket\"]") && dashboard.includes("transports: [\"websocket\"]")); ok("dedicated bind", server.includes("127.0.0.1")); ok("healthz", server.includes("/healthz")); ok("redis env", read("lib/realtime/redis.ts").includes("REDIS_URL")); ok("rediss production", read("lib/realtime/redis.ts").includes("rediss://")); ok("no secret log", !worker.includes("REDIS_URL") && !server.includes("REDIS_URL"));
ok("origin validation", auth.includes("originAllowed") && server.includes("originAllowed")); ok("no wildcard origin", !server.includes('origin: "*"')); ok("canonical cookie auth", auth.includes("verifyCanonicalToken") && auth.includes("sessionCookieName")); ok("authVersion", auth.includes("authVersion")); ok("actor namespaces", server.includes("/driver") && server.includes("/admin") && server.includes("/passenger")); ok("server rooms", server.includes("socket.join(room)") && server.includes("socket.join(\"admins\")")); ok("no join room", !server.includes("join-room")); ok("no query identity", !server.includes("query.driverId"));
ok("safe contracts", contracts.includes("eventId") && contracts.includes("occurredAt")); ok("domain routing", worker.includes("eventTypeForDomain")); ok("no exact address payload", !contracts.includes("pickupAddress") && !contracts.includes("dropoffAddress")); ok("no location streaming", !worker.includes("currentLat") && !worker.includes("currentLng")); ok("rest authority client", dashboard.includes("fetchDriverData(driver.id, true)")); ok("accept remains rest", !server.includes("acceptRide"));
ok("outbox model", schema.includes("model OutboxEvent")); ok("outbox attempts", schema.includes("attempts Int")); ok("outbox lease", schema.includes("claimedAt DateTime?")); ok("outbox error", schema.includes("lastError String?")); ok("outbox retry time", schema.includes("nextAttemptAt DateTime?")); ok("notification model", schema.includes("model Notification")); ok("notification dedupe", schema.includes("dedupeKey String @unique")); ok("notification indexes", schema.includes("recipientType, recipientId, readAt"));
ok("claim CAS", relay.includes("updateMany") && relay.includes("PROCESSING")); ok("deterministic outbox jobs", relay.includes("outbox-${event.id}")); ok("queue names centralized", read("lib/realtime/constants.ts").includes("REALTIME_QUEUES")); ok("bounded retry", read("lib/realtime/queues.ts").includes("attempts: 5")); ok("published after route", worker.includes("OUTBOX_STATES.PUBLISHED")); ok("failed inspectable", worker.includes("nextAttemptAt") && worker.includes("lastError")); ok("bounded permanent retry", read("lib/realtime/constants.ts").includes("MAX_OUTBOX_ATTEMPTS") && relay.includes("OUTBOX_STATES.FAILED") && relay.includes("retry_limit_exceeded")); ok("reconcile outbox", worker.includes("relayOutboxOnce"));
ok("offer expiry queue", worker.includes("offer-expiry-") && worker.includes("getOfferExpiryQueue")); ok("persisted expiry", worker.includes("offer.expiresAt")); ok("expiry authoritative", worker.includes("advanceDispatch(offer.bookingId)")); ok("expiry no assignment", !worker.includes("booking.update({ data: { driverId")); ok("expiry reconciliation", worker.includes("status: \"PENDING\", expiresAt")); ok("expiry no browser timer", !dashboard.includes("expiresAt") || !dashboard.includes("setTimeout"));
ok("driver notifications API", exists("app/api/driver/notifications/route.ts")); ok("admin notifications API", exists("app/api/admin/notifications/route.ts")); ok("driver identity scoped", read("app/api/driver/notifications/route.ts").includes("auth.actor.id")); ok("admin identity scoped", read("app/api/admin/notifications/route.ts").includes("auth.actor.id")); ok("read ownership", read("lib/notifications.ts").includes("recipientId")); ok("dedupe upsert", read("lib/notifications.ts").includes("upsert")); ok("csrf mutations", read("app/api/driver/notifications/[id]/route.ts").includes("authorizeDriver"));
ok("graceful socket shutdown", server.includes("SIGTERM") && server.includes("io.close")); ok("graceful worker shutdown", worker.includes("SIGTERM") && worker.includes("outboxWorker.close")); ok("safe logs", worker.includes("job_failed") && !worker.includes("message: error.message")); ok("multi-language structure", read("lib/notifications.ts").includes("type") && read("lib/notifications.ts").includes("data")); ok("phase 3e excluded", !worker.match(/geofenc|turn-by-turn|route drawing|navigation/i)); ok("no fare logic", !worker.includes("pricing") && !server.includes("fare")); ok("phase 3c retained", read("lib/automatic-dispatch.ts").includes("advanceDispatch"));
console.log(`Phase 3D checks passed: ${checks} (static/source assertions; Redis/Mongo/browser integration not run)`);
