const fs = require("fs");
const read = (file) => fs.readFileSync(file, "utf8");
const schema = read("prisma/schema.prisma");
const service = read("lib/admin-operations.ts");
const ui = read("app/admin/operations/page.tsx");
const layout = read("app/admin/layout.tsx");
const pkg = read("package.json");
const checklist = read("PHASE_3H_CHECKLIST.md");
const files = [
  "app/api/admin/operations/overview/route.ts",
  "app/api/admin/operations/rides/route.ts",
  "app/api/admin/operations/drivers/route.ts",
  "app/api/admin/operations/scheduled/route.ts",
  "app/api/admin/operations/alerts/route.ts",
  "app/api/admin/operations/audit/route.ts",
  "app/api/admin/operations/ledger/route.ts",
  "app/api/admin/operations/dispatch/retry/route.ts",
  "app/api/admin/operations/assign/route.ts",
  "app/api/admin/operations/release/route.ts",
].map(read);
const checks = [
  ["checklist exists", fs.existsSync("PHASE_3H_CHECKLIST.md")],
  ["architecture lock exists", checklist.includes("Final Phase 3H architecture")],
  ["audit model exists", schema.includes("model AdminAuditEvent")],
  ["audit append fields", ["adminId", "action", "targetType", "targetId", "reason", "requestId", "outcome", "safeMetadata"].every((x) => schema.includes(x))],
  ["audit unique request", schema.includes("requestId String @unique")],
  ["audit indexes", schema.includes("@@index([adminId, createdAt])") && schema.includes("@@index([targetType, targetId, createdAt])")],
  ["booking ride relation", schema.includes("rideRequests RideRequest[]")],
  ["driver ride relation", schema.includes("rideRequests    RideRequest[]")],
  ["ride request relations", schema.includes("booking Booking @relation") && schema.includes("driver Driver @relation")],
  ["overview route exists", fs.existsSync("app/api/admin/operations/overview/route.ts")],
  ["rides route exists", fs.existsSync("app/api/admin/operations/rides/route.ts")],
  ["drivers route exists", fs.existsSync("app/api/admin/operations/drivers/route.ts")],
  ["scheduled route exists", fs.existsSync("app/api/admin/operations/scheduled/route.ts")],
  ["alerts route exists", fs.existsSync("app/api/admin/operations/alerts/route.ts")],
  ["audit route exists", fs.existsSync("app/api/admin/operations/audit/route.ts")],
  ["ledger route exists", fs.existsSync("app/api/admin/operations/ledger/route.ts")],
  ["retry route exists", fs.existsSync("app/api/admin/operations/dispatch/retry/route.ts")],
  ["assign route exists", fs.existsSync("app/api/admin/operations/assign/route.ts")],
  ["release route exists", fs.existsSync("app/api/admin/operations/release/route.ts")],
  ["all routes admin auth", files.every((x) => x.includes("authorizeAdmin"))],
  ["all mutation routes post", files.slice(-3).every((x) => x.includes("export async function POST"))],
  ["no client admin identity", !files.join("\n").includes("adminId:")],
  ["reason schema", files.slice(-3).every((x) => x.includes("reason") && x.includes("max(500)"))],
  ["operations bounded", service.includes("boundedPage") && service.includes("take: take + 1")],
  ["server ride filters", service.includes("where.bookingRef") && service.includes("dispatchStatus")],
  ["driver presence central", service.includes("evaluateDriverPresence") && service.includes("operationalPresence")],
  ["freshness central", service.includes("isLocationFresh") && service.includes("SCHEDULED_MARKET_CONFIG")],
  ["overview actual states", service.includes("DISPATCH_EXHAUSTED") && service.includes("SEARCHING_DRIVER")],
  ["failed outbox surfaced", service.includes('state: "FAILED"')],
  ["scheduled monitoring", service.includes("listScheduledOperations") && service.includes("scheduledRide: true")],
  ["ledger read only", service.includes("listLedgerSupport") && !service.includes("driverLedgerEntry.update") && !service.includes("driverLedgerEntry.delete")],
  ["dispatch reuses engine", service.includes("startAutomaticDispatch") && service.includes("startScheduledRecoveryDispatch")],
  ["dispatch eligibility reused", service.includes("bookingDispatchEligibility") && service.includes("driverCompatibility")],
  ["assignment transaction", service.includes("prisma.$transaction") && service.includes("booking.updateMany")],
  ["assignment CAS", service.includes("driverId: null") && service.includes("ASSIGNABLE_BOOKING_STATUSES")],
  ["assignment cleanup", service.includes('status: "CANCELLED"') && service.includes("ADMIN_OFFER_CANCELLED")],
  ["assignment outbox", service.includes("ADMIN_MANUAL_ASSIGNMENT")],
  ["assignment audit", service.includes("MANUAL_ASSIGNMENT") && service.includes("recordAudit(tx")],
  ["safe scheduled release", service.includes("releaseScheduledAssignment") && service.includes("SCHEDULED_ASSIGNMENT_RELEASE")],
  ["no generic release", !service.includes("UNASSIGN_DRIVER")],
  ["audit dedupe", service.includes("requestId") && service.includes("P2002")],
  ["audit reason sanitizer", service.includes("replace(/[<>]/g")],
  ["alerts centralized", service.includes("deriveOperationalAlerts")],
  ["alerts severity", service.includes("CRITICAL") && service.includes("WARNING") && service.includes("INFO")],
  ["alerts resolve derived", !service.includes("alert.create")],
  ["no unsafe outbox retry", !files.join("\n").includes("outboxEvent.update")],
  ["audit bounded view", service.includes("listAdminAudit") && service.includes("take")],
  ["ledger privacy projection", service.includes("idempotencyKey: true") && !service.includes("metadata: true")],
  ["no passenger list data", !service.includes("customerPhone") && !service.includes("parentPrimaryPhone")],
  ["no password data", !service.includes("passwordHash: true")],
  ["multi-city field", service.includes("marketTimezone")],
  ["no hardcoded coords", !ui.includes("48.1486") && !ui.includes("17.1077")],
  ["no map architecture", !ui.includes("GoogleMap")],
  ["realtime signal/refetch", ui.includes("socket.on") && ui.includes("setTimeout") && ui.includes("load()")],
  ["no socket mutation", !ui.includes("socket.emit")],
  ["operations nav", layout.includes("/admin/operations") && layout.includes("admin.operations")],
  ["responsive grid", ui.includes("grid-cols-2") && ui.includes("lg:")],
  ["accessible headings", ui.includes("aria-labelledby") && ui.includes("caption")],
  ["visible focus", ui.includes("focus-visible:outline")],
  ["admin UI server fetch", ui.includes('csrfFetch("admin"')],
  ["no payouts", !service.includes("payout") && !ui.includes("payout")],
  ["no wallet", !service.includes("wallet") && !ui.includes("wallet")],
  ["no bank", !service.includes("bank") && !ui.includes("bank")],
  ["no phase 3h duplicate app", !fs.existsSync("app/admin-v2")],
  ["read-only plan exists", fs.existsSync("PHASE_3H_PRODUCTION_READ_ONLY_QUERY_PLAN.md")],
  ["package script", pkg.includes("test:phase3h")],
  ["phase 3g preserved", pkg.includes("test:phase3g")],
  ["translations en", read("lib/i18n/translations/en.ts").includes("admin.operations")],
  ["translations sk", read("lib/i18n/translations/sk.ts").includes("admin.operations")],
  ["translations de", read("lib/i18n/translations/de.ts").includes("admin.operations")],
  ["translations uk", read("lib/i18n/translations/uk.ts").includes("admin.operations")],
];
const extraChecks = [
  ["overview active metric", service.includes("activeRides")],
  ["overview unassigned metric", service.includes("unassignedImmediate")],
  ["overview searching metric", service.includes("searching")],
  ["overview exhausted metric", service.includes("exhausted")],
  ["overview scheduled metric", service.includes("upcomingScheduled")],
  ["overview online metric", service.includes("onlineDrivers")],
  ["overview available metric", service.includes("availableDrivers")],
  ["overview busy metric", service.includes("busyDrivers")],
  ["overview stale metric", service.includes("staleLocationDrivers")],
  ["overview outbox metric", service.includes("failedOutbox")],
  ["overview offers metric", service.includes("staleOffers")],
  ["ride service filter", service.includes("serviceType =")],
  ["ride status filter", service.includes("where.status = status")],
  ["ride assignment filter", service.includes('params.get("assigned")')],
  ["ride scheduled filter", service.includes('params.get("scheduled")')],
  ["ride cursor ordering", service.includes('createdAt: "desc"') && service.includes('id: "desc"')],
  ["driver search filter", service.includes("fullName = { contains")],
  ["driver state filter", service.includes("presenceState === state")],
  ["driver active booking", service.includes("activeBooking")],
  ["driver coordinates admin projection", service.includes("currentLat") && service.includes("currentLng")],
  ["scheduled pickup filter", service.includes("pickupAt: { gt: now }")],
  ["ledger gross projection", service.includes("grossAmountMinor: true")],
  ["ledger commission projection", service.includes("commissionAmountMinor: true")],
  ["ledger net projection", service.includes("netAmountMinor: true")],
  ["audit outcome", schema.includes("outcome String")],
  ["audit createdAt", schema.includes("createdAt DateTime @default(now())")],
  ["audit target index", schema.includes("@@index([targetType, targetId, createdAt])")],
  ["audit action index", schema.includes("@@index([action, createdAt])")],
  ["request replay lookup", service.includes("existingAudit")],
  ["request unique conflict", service.includes('error?.code === "P2002"')],
  ["assignment driver CAS", service.includes("isOnTrip: false")],
  ["assignment booking CAS", service.includes("driverId: null")],
  ["assignment status transition", service.includes('status: "ASSIGNED"')],
  ["assignment acceptedAt", service.includes("acceptedAt: new Date()")],
  ["offer cancellation event", service.includes("ADMIN_OFFER_CANCELLED")],
  ["dispatch retry audit", service.includes('action: "DISPATCH_RETRY"')],
  ["release audit", service.includes('action: "SCHEDULED_ASSIGNMENT_RELEASE"')],
  ["alerts no persistence", !service.includes("adminAlert.create")],
  ["socket debounce", ui.includes("700")],
  ["socket close cleanup", ui.includes("socket.close()")],
  ["ui retry button", ui.includes("Retry dispatch")],
  ["ui release button", ui.includes("Release scheduled")],
  ["ui assignment button", ui.includes("Assign driver")],
  ["ui reason max", ui.includes("maxLength={500}")],
  ["ui no financial controls", !ui.includes("Edit ledger")],
  ["ui no force status", !ui.includes("Set status")],
  ["ui status text", ui.includes("ride.status")],
  ["ui alert role", ui.includes('role="alert"')],
  ["ui touch target", ui.includes("min-h-11")],
  ["ui no passenger phone", !ui.includes("customerPhone")],
  ["ui no coordinates", !ui.includes("currentLat")],
  ["phase3h plan no execution", read("PHASE_3H_PRODUCTION_READ_ONLY_QUERY_PLAN.md").includes("Do not execute")],
  ["phase3h plan no pii", read("PHASE_3H_PRODUCTION_READ_ONLY_QUERY_PLAN.md").includes("exclude passenger")],
  ["no connect transfer", !service.includes("Connect") && !ui.includes("Connect")],
  ["no sepa", !service.includes("SEPA") && !ui.includes("SEPA")],
  ["no tax engine", !service.includes("tax engine") && !ui.includes("tax engine")],
  ["no fleet settlement", !service.includes("settlement") && !ui.includes("settlement")],
  ["no arbitrary status API", !fs.existsSync("app/api/admin/operations/status")],
  ["no audit delete route", !fs.existsSync("app/api/admin/operations/audit/[id]")],
  ["no ledger mutation route", !fs.existsSync("app/api/admin/operations/ledger/[id]")],
  ["no map dependency", !fs.existsSync("app/admin/operations/map")],
  ["schema no payout fields", !schema.includes("withdrawable")],
  ["children flag unchanged", read("scripts/phase3a-runtime-check.js").includes("Children disabled")],
  ["ux1 source preserved", read("scripts/ux1-check.cjs").includes("136")],
  ["phase3g source preserved", fs.existsSync("scripts/phase3g-check.cjs")],
  ["phase3f source preserved", fs.existsSync("scripts/phase3f-check.cjs")],
  ["phase3e source preserved", fs.existsSync("scripts/phase3e-check.cjs")],
  ["phase3d source preserved", fs.existsSync("scripts/phase3d-check.cjs")],
  ["phase3c source preserved", fs.existsSync("scripts/phase3c-check.cjs")],
  ["phase3b source preserved", fs.existsSync("scripts/phase3b-check.cjs")],
  ["phase3a source preserved", fs.existsSync("scripts/phase3a-security-check.js")],
  ["admin nav remains existing", layout.includes("/admin/dashboard") && layout.includes("/admin/bookings")],
  ["vehicle nav remains existing", layout.includes("/admin/vehicles")],
  ["pricing nav remains existing", layout.includes("/admin/pricing")],
  ["financial nav remains existing", layout.includes("/admin/financial")],
];
checks.push(...extraChecks);
let passed = 0;
for (const [name, ok] of checks) {
  if (!ok) { console.error("FAIL " + name); process.exitCode = 1; } else passed += 1;
}
if (process.exitCode) process.exit(1);
console.log("Phase 3H checks: " + passed + "/" + checks.length + " passed");
