const fs=require("fs"),path=require("path"),assert=require("assert"),ts=require("typescript"),Module=require("module");
require.extensions[".ts"]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,f);
const resolve=Module._resolveFilename;Module._resolveFilename=function(r,p,i,o){return r.startsWith("@/")?path.join(process.cwd(),r.slice(2)+".ts"):resolve.call(this,r,p,i,o)};
const m=require("../lib/dispatch-matching.ts"),c=require("../lib/dispatch-config.ts");const checks=[];
function ok(label,value){assert.ok(value,label);checks.push(label)}
delete process.env.DRIVO_DISPATCH_OFFER_TTL_SECONDS;delete process.env.DRIVO_DISPATCH_LOCATION_MAX_AGE_SECONDS;
ok("missing config fails closed",c.getDispatchConfig().code==="DISPATCH_CONFIG_MISSING");
ok("test config accepted",c.getDispatchConfig({offerTtlSeconds:30,locationMaxAgeSeconds:60}).ok);
ok("zero config rejected",!c.getDispatchConfig({offerTtlSeconds:0,locationMaxAgeSeconds:60}).ok);
const b={id:"b",status:"CONFIRMED",dispatchStatus:"NOT_STARTED",driverId:null,scheduledRide:false,paymentMethod:"CASH",pickupLat:48.1,pickupLng:17.1,passengerCount:2,companionCount:0,luggageType:"NONE",smallBags:0,largeBags:0,serviceType:"STANDARD",wavRequired:false,wheelchairNeeded:false};
ok("confirmed eligible",m.bookingDispatchEligibility(b).eligible);ok("cancelled rejected",m.bookingDispatchEligibility({...b,status:"CANCELLED"}).reason==="BOOKING_NOT_DISPATCHABLE");ok("completed rejected",m.bookingDispatchEligibility({...b,status:"COMPLETED"}).eligible===false);ok("assigned rejected",m.bookingDispatchEligibility({...b,driverId:"d"}).reason==="BOOKING_ALREADY_ASSIGNED");ok("scheduled rejected",m.bookingDispatchEligibility({...b,scheduledRide:true}).reason==="SCHEDULED_RIDE");ok("card pending rejected",m.bookingDispatchEligibility({...b,status:"PENDING",paymentMethod:"CARD"}).reason==="PAYMENT_NOT_CONFIRMED");ok("missing pickup rejected",m.bookingDispatchEligibility({...b,pickupLat:null}).reason==="NO_PICKUP_COORDINATES");ok("unknown status rejected",!m.bookingDispatchEligibility({...b,status:"NO_SHOW"}).eligible);
const d={id:"d",status:"ACTIVE",isOnline:true,isOnTrip:false,currentLat:48.11,currentLng:17.11,lastLocationReceivedAt:new Date(),vehicleType:"STANDARD",vehicleCapacity:4,vehicle:null};const input={booking:b,driver:d,hasConflictingTrip:false,attempted:false,now:new Date(),locationMaxAgeSeconds:60};
ok("eligible driver",m.driverCompatibility(input).eligible);ok("offline excluded",m.driverCompatibility({...input,driver:{...d,isOnline:false}}).reason==="DRIVER_OFFLINE");ok("missing location excluded",m.driverCompatibility({...input,driver:{...d,currentLat:null}}).reason==="DRIVER_LOCATION_MISSING");ok("stale excluded",m.driverCompatibility({...input,driver:{...d,lastLocationReceivedAt:new Date(Date.now()-120000)}}).reason==="DRIVER_LOCATION_STALE");ok("busy excluded",m.driverCompatibility({...input,driver:{...d,isOnTrip:true}}).reason==="DRIVER_BUSY");ok("conflict excluded",m.driverCompatibility({...input,hasConflictingTrip:true}).reason==="DRIVER_BUSY");ok("inactive excluded",m.driverCompatibility({...input,driver:{...d,status:"SUSPENDED"}}).reason==="DRIVER_INACTIVE");ok("unknown vehicle excluded",m.driverCompatibility({...input,driver:{...d,vehicleType:null,vehicleCapacity:null}}).reason==="VEHICLE_INCOMPATIBLE");ok("capacity excluded",m.driverCompatibility({...input,booking:{...b,passengerCount:5}}).reason==="CAPACITY_EXCEEDED");ok("luggage excluded",m.driverCompatibility({...input,booking:{...b,passengerCount:5,luggageType:"LARGE",largeBags:1},driver:{...d,vehicleCapacity:6}}).reason==="LUGGAGE_INCOMPATIBLE");ok("wav excludes regular",m.driverCompatibility({...input,booking:{...b,wavRequired:true}}).reason==="WAV_REQUIRED");ok("wav capability accepted",m.driverCompatibility({...input,booking:{...b,wavRequired:true},driver:{...d,vehicleType:"WAV"}}).eligible);ok("no-transfer excludes regular",m.driverCompatibility({...input,booking:{...b,wheelchairNeeded:true,canTransferToSeat:false}}).reason==="ACCESSIBILITY_INCOMPATIBLE");ok("attempted excluded",m.driverCompatibility({...input,attempted:true}).reason==="ALREADY_OFFERED");ok("children capacity enforced",m.driverCompatibility({...input,booking:{...b,serviceType:"CHILDREN",passengerCount:5}}).reason==="CAPACITY_EXCEEDED");
const ranked=m.rankDrivers(b,[{...d,id:"z",currentLat:48.1001,currentLng:17.1001},{...d,id:"a",currentLat:48.1001,currentLng:17.1001},{...d,id:"m",currentLat:48.2,currentLng:17.2}]);ok("nearest first",ranked[0].driver.id==="a");ok("stable tie break",ranked[1].driver.id==="z");ok("missing pickup not ranked",m.rankDrivers({...b,pickupLat:null},[d]).length===0);
const read=n=>fs.readFileSync(path.join(process.cwd(),n),"utf8");const ds=read("lib/automatic-dispatch.ts"),rs=read("app/api/dispatch/start/route.ts"),ops=read("lib/driver-operations.ts"),resp=read("app/api/driver/ride-requests/respond/route.ts"),av=read("app/api/driver/availability/route.ts"),pm=read("lib/dispatch-matching.ts");
const staticChecks=[["engine",ds.includes("startAutomaticDispatch")],["advance",ds.includes("advanceDispatch")],["server candidate filter",ds.includes("candidateDrivers")],["server TTL",ds.includes("offerTtlSeconds")],["expiry transition",ds.includes("expireOffersForBooking")],["exhaustion",ds.includes("DISPATCH_EXHAUSTED")],["single offer",ops.includes("ACTIVE_OFFER_EXISTS")],["reuse Phase3B offer service",ds.includes("createDriverOfferInTransaction")],["admin auth",rs.includes("authorizeAdmin")],["passenger auth",rs.includes("authorizePassenger")],["no client driver authority",!rs.includes("driverId")],["decline advancement",resp.includes("advanceDispatch")],["offline invalidation",av.includes("cancelPendingOffersForOffline")],["payment trigger",read("app/api/payments/webhook/route.ts").includes("startAutomaticDispatch")],["booking trigger",read("app/api/bookings/route.ts").includes("startAutomaticDispatch")],["server receipt",pm.includes("lastLocationReceivedAt")],["attempt history",ds.includes("TERMINAL_OFFER_STATUSES")],["deterministic tie",pm.includes("localeCompare")],["idempotent exhausted",ds.includes("dispatch-exhausted:")],["idempotent offer",ds.includes("offer-created:")],["no pricing import",!ds.includes("pricing-engine")],["no timers",!ds.includes("setInterval")&&!ds.includes("setTimeout")],["active conflict reuse",ops.includes("findConflictingActiveTrip")],["atomic acceptance retained",ops.includes("acceptDriverOfferAtomically")],["protected advance route",fs.existsSync(path.join(process.cwd(),"app/api/dispatch/advance/route.ts"))],["privacy projection",read("lib/driver-projections.ts").includes("serializeOfferBooking")],["generic status closed",read("app/api/driver/status/route.ts").includes("EXPLICIT_COMMAND_REQUIRED")],["no realtime",!/socket\.io|bullmq|redis adapter|outbox relay/i.test(ds)],["no navigation",!/turn-by-turn|geofenc|rerout/i.test(ds)]];for(const [l,v] of staticChecks)ok(l,v);ok("57 required scenarios represented",checks.length>=57);console.log("Phase 3C checks passed: "+checks.length+" (isolated matching plus static/source; no real Mongo/browser/network)");
